# Generated by Django 4.2.27 on 2026-01-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("entrada", "Entrada"), ("saida", "Saída")],
                        max_length=10,
                    ),
                ),
                (
                    "pessoa",
                    models.CharField(
                        choices=[
                            ("IAN", "Ian"),
                            ("JULIA", "Julia"),
                            ("JUNTOS", "Juntos"),
                        ],
                        max_length=10,
                    ),
                ),
                ("origem", models.CharField(max_length=255)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
