# Generated by Django 4.2.27 on 2026-01-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pessoa",
                    models.CharField(
                        choices=[
                            ("IAN", "Ian"),
                            ("JULIA", "Julia"),
                            ("JUNTOS", "Juntos"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("senha", models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
